apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend
  labels:
    app: recommend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommend
  template:
    metadata:
      labels:
        app: recommend
    spec:
      containers:
        - name: recommend
          image: 357806352922.dkr.ecr.ap-northeast-2.amazonaws.com/moine_recommend:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: moine-backend-configmap
