apiVersion: v1
kind: Service
metadata:
  name: recommend-backend-svc
  labels:
    app: recommend-backend-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: recommend
      protocol: TCP
      targetPort: 8080
  selector:
    app: recommend
